### PR TITLE
Add new, short suite for quick CI turnaround

### PR DESCRIPTION
**Pull request by falkecarlsen**
Does what it says on the tin :tm: 

If paths of any declared bench is wrong, the `cargo test --benches` flow fails, but we don't waste time on running each bench once for every CI check.

In future for real benchmarks, the user has to disable this suite - but it's described in comment directly at criterion_main function call.

### CODE REVIEW

**Comment by falkecarlsen** [comment]
CI for benches now takes ~2:45 which is 13 seconds less than ordinary test-suite.

**Review by asger-weirsoee — APPROVED** [review]
5% faster. I mean it is something 🤷‍♂️

**Comment by falkecarlsen** [comment]
> 5% faster. I mean it is something man_shrugging

No, you misunderstand - last run on main took 36 minutes: https://github.com/d702e20/CGAAL/runs/2710055687
So it's 92% faster now.

**Comment by asger-weirsoee** [comment]
Ah, well then I misunderstood the  "~2:45 which is 13 seconds less than ordinary test-suite." then ~

**Review by NicEastvillage — APPROVED** [review]

**Pull request merged**
