### PR TITLE
Add random DFS search strategy

### LINKED ISSUE #218: Add random depth-first search strategy (RDFS)
One of TAPAAL's best search strategies is the random depth-first search strategy (RDFS), which is a typical DFS using a stack, but groups of successors are shuffled before they are pushed to the stack. We should add that to CGAAL and test its performance.

### PR DESCRIPTION
**Pull request by falkecarlsen**
Resolves #218 

Prelim results on 5 player mexi on all three formulae:
```
(default) Search strategy 'rdfs' with backpropagation prioritisation: true
mexican_standoff_5p_1hp_lcgs_survive_threads/1
                        time:   [124.63 ms 127.97 ms 133.71 ms]
                        change: [-12.874% -7.4688% -1.1930%] (p = 0.04 < 0.05)
                        Performance has improved.
mexican_standoff_5p_1hp_lcgs_survive_threads/2
                        time:   [123.64 ms 127.77 ms 131.05 ms]
                        change: [-10.489% -6.9211% -2.6805%] (p = 0.01 < 0.05)
                        Performance has improved.
mexican_standoff_5p_1hp_lcgs_survive_threads/4
                        time:   [90.223 ms 95.027 ms 104.50 ms]
                        change: [+1.9778% +8.4700% +14.975%] (p = 0.02 < 0.05)
                        Performance has regressed.
mexican_standoff_5p_1hp_lcgs_survive_threads/8
                        time:   [94.321 ms 95.613 ms 96.735 ms]
                        change: [-3.9280% -1.8858% +0.0811%] (p = 0.11 > 0.05)
                        No change in performance detected.

(default) Search strategy 'rdfs' with backpropagation prioritisation: true
mexican_standoff_5p_1hp_lcgs_suicide_threads/1
                        time:   [144.14 ms 154.34 ms 162.37 ms]
                        change: [-3.2177% +5.5169% +15.231%] (p = 0.27 > 0.05)
                        No change in performance detected.
mexican_standoff_5p_1hp_lcgs_suicide_threads/2
                        time:   [160.46 ms 165.51 ms 172.51 ms]
                        change: [-0.6761% +5.6450% +12.137%] (p = 0.10 > 0.05)
                        No change in performance detected.
Found 2 outliers among 10 measurements (20.00%)
  2 (20.00%) high mild
mexican_standoff_5p_1hp_lcgs_suicide_threads/4
                        time:   [148.74 ms 160.01 ms 167.03 ms]
                        change: [-11.192% -4.2601% +2.5668%] (p = 0.29 > 0.05)
                        No change in performance detected.
mexican_standoff_5p_1hp_lcgs_suicide_threads/8
                        time:   [144.21 ms 146.68 ms 151.27 ms]
                        change: [-10.531% -5.0504% +1.4421%] (p = 0.16 > 0.05)
                        No change in performance detected.
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high mild

(default) Search strategy 'rdfs' with backpropagation prioritisation: true
mexican_standoff_5p_1hp_lcgs_teamwork_threads/1
                        time:   [476.29 ms 488.14 ms 503.20 ms]
                        change: [-4.4127% -1.6723% +1.3156%] (p = 0.32 > 0.05)
                        No change in performance detected.
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high severe
mexican_standoff_5p_1hp_lcgs_teamwork_threads/2
                        time:   [434.14 ms 448.36 ms 461.55 ms]
                        change: [-2.8001% +2.5593% +8.7169%] (p = 0.41 > 0.05)
                        No change in performance detected.
mexican_standoff_5p_1hp_lcgs_teamwork_threads/4
                        time:   [388.02 ms 396.53 ms 405.27 ms]
                        change: [-6.8646% -3.7017% -0.1820%] (p = 0.06 > 0.05)
                        No change in performance detected.
mexican_standoff_5p_1hp_lcgs_teamwork_threads/8
                        time:   [468.78 ms 479.86 ms 493.32 ms]
                        change: [-3.2150% +2.2734% +8.3975%] (p = 0.46 > 0.05)
                        No change in performance detected.
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high mild
```

### CODE REVIEW

**Comment by NicEastvillage** [comment]
Where did you find the hashmap trick? When I search for "rust shuffle vec efficient" all answers point to <https://rust-random.github.io/rand/rand/seq/trait.SliceRandom.html>

**Comment by falkecarlsen** [comment]
> Where did you find the hashmap trick? When I search for "rust shuffle vec efficient" all answers point to https://rust-random.github.io/rand/rand/seq/trait.SliceRandom.html

https://users.rust-lang.org/t/solved-efficient-rust-random-shuffle-of/25350/8

**Comment by NicEastvillage** [comment]
Interesting. They are discussing a case with 300_000_000 elements. Our list is typically small, `O(#players * #actions)`, and I wonder if that makes a difference. It may be worth benchmarking the hashmap approach against the `RandomSlice::shuffle()`.

**Comment by falkecarlsen** [comment]
> Interesting. They are discussing a case with 300_000_000 elements. Our list is typically small, `O(#players * #actions)`, and I wonder if that makes a difference. It may be worth benchmarking the hashmap approach against the `RandomSlice::shuffle()`.

Benchmarking on: 
    prismlike_rc3_1_threads,
    prismlike_rc3_3_threads,
    mexican_standoff_5p_1hp_lcgs_survive_threads,
    mexican_standoff_5p_1hp_lcgs_suicide_threads,
    mexican_standoff_5p_1hp_lcgs_teamwork_threads,

Results: https://gist.github.com/falkecarlsen/52832b08c08b4080faf2fd7adeb23fe8
Was run on my machine while not interacting with it, but some variability to be expected.

Takeaways:
- Hashmap-method gets better with more cores - up to 11% speedup - on rc_3_1. Pretty telling distribution for rc3_1/16t:
image
- Noisy results on rc3_3, fig 1 (rc_3_3/2t): Hashmap results are more variable on one thread but skewed towards shorter runtime, so that's fine. Fig 2(rc_3_3/8t): Same characteristica, but reversed.
image
image
- Hashmap-method worse or equal on mexi_5p_1hp on most thread configurations across all three formulae

The variance we're seeing is probably due to salting of the hash-algorithm which is AFAIK once per run, where rand invokes the RNG every time new edges are queued. We should do more testing, but on this limited suite, it seems rand is the right approach. That is the implementation that we go with, barring any further testing.

**Review by NicEastvillage — APPROVED** [review]

**Pull request merged**
